ok

diff --git a/.local/bin/screenrecord b/.local/bin/screenrecord
--- a/.local/bin/screenrecord
+++ b/.local/bin/screenrecord
@@ -18,10 +18,26 @@ i3blocks_signal() {
   fi
 }
 
-notify_saved() {
-  if [ "$(notify-send "Screen recording saved." "${path_out}" --app-name="${script}" --action="LOCATE=Locate" --wait)" ]; then
-    file_manager_desktop "$path_out"
-  fi
+saved() {
+  i3blocks_signal 1>/dev/null 2>/dev/null & disown
+
+  (
+    if [ "$(notify-send "Screen recording saved." "${path_out}" --app-name="${script}" --action="LOCATE=Locate" --wait)" ]; then
+      file_manager_desktop "$path_out"
+    fi
+  ) 1>/dev/null 2>/dev/null & disown
+
+  echo "${script}: Screen recording saved at ${path_out}"
+}
+
+failed() {
+  i3blocks_signal 1>/dev/null 2>/dev/null & disown
+
+  notify-send "Screen recording failed." --app-name="${script}" --urgency="critical" 1>/dev/null 2>/dev/null & disown
+
+  echo "${script}: Screen recording failed." 1>&2
+
+  exit "2"
 }
 
 not_implemented() {
@@ -35,6 +51,8 @@ not_implemented() {
 }
 
 countdown() {
+  i3blocks_signal "wait" 1>/dev/null 2>/dev/null & disown
+
   if [ "$delay" = "0" ]; then
     return
   fi
@@ -53,120 +71,102 @@ countdown() {
 }
 
 if [ "${WAYLAND_DISPLAY:-""}" ]; then
-  if [ "${capture_mode:-""}" = "stop" ]; then
-    set +e
-    pkill -SIGINT -f "wf-recorder"
-    pkill -SIGINT -f "slurp"
-    set -e
-
-    i3blocks_signal 1>/dev/null 2>/dev/null & disown
-
-    exit "0"
-  fi
-
-  if [ "$(pidof "wf-recorder")" ] || [ "$(pidof "slurp")" ]; then
-    exit "3"
-  fi
-
-  record() {
-    ptr_coord=""
-    jq_rect_map='"\(.x),\(.y) \(.width)x\(.height)"'
-
-    case "$capture_mode" in
-      "area")
-        ptr_coord="$(set +e; slurp; set -e)"
-      ;;
-      "output")
-        ptr_coord="$(set +e; swaymsg -t "get_outputs" | jq -r ".. | select(.active?).rect | ${jq_rect_map}" | slurp; set -e)"
-      ;;
-      "output_focused")
-        ptr_coord="$(set +e; swaymsg -t "get_outputs" | jq -r ".. | select(.focused?).rect | ${jq_rect_map}"; set -e)"
-      ;;
-      "window")
-        ptr_coord="$(set +e; swaymsg -t "get_tree" | jq -r ".. | select(.pid? and .visible?).rect | ${jq_rect_map}" | slurp; set -e)"
-      ;;
-      "window_focused")
-        ptr_coord="$(set +e; swaymsg -t "get_tree" | jq -r ".. | select(.type? and .focused?).rect | ${jq_rect_map}"; set -e)"
-      ;;
-      "workspace")
-        ptr_coord="$(set +e; swaymsg -t "get_workspaces" | jq -r ".. | select(.visible? and .type == \"workspace\").rect | ${jq_rect_map}" | slurp; set -e)"
-      ;;
-      "workspace_focused")
-        ptr_coord="$(set +e; swaymsg -t "get_workspaces" | jq -r ".. | select(.focused? and .type == \"workspace\").rect | ${jq_rect_map}"; set -e)"
-      ;;
-    esac
-
-    if [ -z "$ptr_coord" ]; then
-      notify-send "No screen area selected." --app-name="${script}" --urgency="critical" 1>/dev/null 2>/dev/null & disown
-
-      echo "${script}: No screen area selected." 1>&2
-
-      exit "2"
-    fi
-
-    ptr_coord_x="${ptr_coord%,*}"
-    ptr_coord_y="${ptr_coord#*,}"
-    ptr_coord_y="${ptr_coord_y% *}"
-
-    output="$(
-      swaymsg -rt get_outputs | jq -r \
-        ".[] | select((${ptr_coord_x} >= .rect.x) and (${ptr_coord_x} < .rect.x + .rect.width) and (${ptr_coord_y} >= .rect.y) and (${ptr_coord_y} < .rect.y + .rect.height))"
-    )"
-
-    output_name="$(echo "$output" | jq -r ".name")"
-    output_transform="$(echo "$output" | jq -r ".transform")"
-
-    rec_transpose=""
-
-    case "$output_transform" in
-      "180")
-        rec_transpose="-F transpose=1"
-      ;;
-      "90")
-        rec_transpose="-F transpose=2"
-      ;;
-    esac
-
-    countdown
-
-    i3blocks_signal "wait" 1>/dev/null 2>/dev/null & disown
-
-    case "$capture_mode" in
-      "output")
-        if ! wf-recorder --audio --codec=libx264rgb "$rec_transpose" --output="$output_name" --file="$path_out"; then
-          notify-send "Screen recording failed." --app-name="${script}" --urgency="critical" 1>/dev/null 2>/dev/null & disown
-
-          echo "${script}: Screen recording failed." 1>&2
-
-          exit "2"
-        fi
-      ;;
-      *)
-        if ! wf-recorder --audio --codec=libx264rgb "$rec_transpose" --geometry="$ptr_coord" --file="$path_out"; then
-          notify-send "Screen recording failed." --app-name="${script}" --urgency="critical" 1>/dev/null 2>/dev/null & disown
-
-          echo "${script}: Screen recording failed." 1>&2
-
-          exit "2"
-        fi
-      ;;
-    esac
-
-    i3blocks_signal 1>/dev/null 2>/dev/null & disown
-
-    notify_saved 1>/dev/null 2>/dev/null & disown
-
-    echo "${script}: Screen recording saved at ${path_out}"
-
-    printf '%s' "$path_out" | wl-copy
-  }
-
   case "$capture_mode" in
-    "all")
-      not_implemented "Wayland" "${1:-""}"
+    "stop")
+      set +e
+      pkill -SIGINT -f "wf-recorder"
+      pkill -SIGINT -f "slurp"
+      set -e
+
+      i3blocks_signal 1>/dev/null 2>/dev/null & disown
+
+      exit "0"
     ;;
-    "area"|"output"|"output_focused"|"window"|"window_focused"|"workspace"|"workspace_focused")
-      record
+    "all"|"area"|"output"|"output_focused"|"window"|"window_focused"|"workspace"|"workspace_focused")
+      if [ "$(pidof "wf-recorder")" ] || [ "$(pidof "slurp")" ]; then
+        exit "3"
+      fi
+
+      ptr_coord=""
+      jq_rect_map='"\(.x),\(.y) \(.width)x\(.height)"'
+
+      case "$capture_mode" in
+        "all")
+          not_implemented "Wayland" "$capture_mode"
+        ;;
+        "area")
+          ptr_coord="$(set +e; slurp; set -e)"
+        ;;
+        "output")
+          ptr_coord="$(set +e; swaymsg -t "get_outputs" | jq -r ".. | select(.active?).rect | ${jq_rect_map}" | slurp; set -e)"
+        ;;
+        "output_focused")
+          ptr_coord="$(set +e; swaymsg -t "get_outputs" | jq -r ".. | select(.focused?).rect | ${jq_rect_map}"; set -e)"
+        ;;
+        "window")
+          ptr_coord="$(set +e; swaymsg -t "get_tree" | jq -r ".. | select(.pid? and .visible?).rect | ${jq_rect_map}" | slurp; set -e)"
+        ;;
+        "window_focused")
+          ptr_coord="$(set +e; swaymsg -t "get_tree" | jq -r ".. | select(.type? and .focused?).rect | ${jq_rect_map}"; set -e)"
+        ;;
+        "workspace")
+          ptr_coord="$(set +e; swaymsg -t "get_workspaces" | jq -r ".. | select(.visible? and .type == \"workspace\").rect | ${jq_rect_map}" | slurp; set -e)"
+        ;;
+        "workspace_focused")
+          ptr_coord="$(set +e; swaymsg -t "get_workspaces" | jq -r ".. | select(.focused? and .type == \"workspace\").rect | ${jq_rect_map}"; set -e)"
+        ;;
+      esac
+
+      if [ -z "$ptr_coord" ]; then
+        notify-send "No screen area selected." --app-name="${script}" --urgency="critical" 1>/dev/null 2>/dev/null & disown
+
+        echo "${script}: No screen area selected." 1>&2
+
+        exit "2"
+      fi
+
+      ptr_coord_x="${ptr_coord%,*}"
+      ptr_coord_y="${ptr_coord#*,}"
+      ptr_coord_y="${ptr_coord_y% *}"
+
+      output="$(
+        swaymsg -rt get_outputs | jq -r \
+          ".[] | select((${ptr_coord_x} >= .rect.x) and (${ptr_coord_x} < .rect.x + .rect.width) and (${ptr_coord_y} >= .rect.y) and (${ptr_coord_y} < .rect.y + .rect.height))"
+      )"
+
+      output_name="$(echo "$output" | jq -r ".name")"
+      output_transform="$(echo "$output" | jq -r ".transform")"
+
+      rec_transpose=""
+
+      case "$output_transform" in
+        "180")
+          rec_transpose="-F transpose=1"
+        ;;
+        "90")
+          rec_transpose="-F transpose=2"
+        ;;
+      esac
+
+      countdown
+
+      case "$capture_mode" in
+        "output")
+          if ! wf-recorder --audio --codec=libx264rgb "$rec_transpose" --output="$output_name" --file="$path_out"; then
+            failed
+          fi
+        ;;
+        *)
+          if ! wf-recorder --audio --codec=libx264rgb "$rec_transpose" --output="$output_name" --geometry="$ptr_coord" --file="$path_out"; then
+            failed
+          fi
+        ;;
+      esac
+
+      saved
+
+      printf '%s' "$path_out" | wl-copy
+
       exit
     ;;
     "-h"|"--help")
